# Render deployment configuration (Docker environment)
services:
  - type: web
    name: solana-fellowship-server
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: RUST_LOG
        value: info
    autoDeploy: true
